# Site settings

title: "News from London"
email: "lbrowning86@gmail.com"
description: "A daily journal by Edward Hyde."
baseurl: ""
url: "http://localhost:4000"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /articles/:title # lowercase separated by hyphens
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"
